Import alchemist, numpy and dask

In [1]:
from alchemist import *
import numpy as np
import dask.array as da


Create an alchemist session, Connect to alchemist and request for workers

In [6]:
als = AlchemistSession()
als.connect_to_alchemist("0.0.0.0", 24960)



Starting Alchemist session ... ready
Connecting to Alchemist at 0.0.0.0:24960 ...Connected to Alchemist!


In [7]:
als.request_workers(3)


Requesting 3 workers from Alchemist
Total allocated 3 workers:
    Worker-1 on C02V25U2HTD6 at 0.0.0.0:24961
    Worker-2 on C02V25U2HTD6 at 0.0.0.0:24962
    Worker-3 on C02V25U2HTD6 at 0.0.0.0:24963
Connecting to Alchemist at 0.0.0.0:24961 ...Connected to Alchemist!
Connecting to Alchemist at 0.0.0.0:24962 ...Connected to Alchemist!
Connecting to Alchemist at 0.0.0.0:24963 ...Connected to Alchemist!


In [8]:
als.list_all_workers()


Listing 3 Alchemist workers:
    Worker-1 on C02V25U2HTD6 at 0.0.0.0:24961
    Worker-2 on C02V25U2HTD6 at 0.0.0.0:24962
    Worker-3 on C02V25U2HTD6 at 0.0.0.0:24963


In [9]:
als.list_active_workers()
als.list_inactive_workers()
als.list_assigned_workers()


Listing 3 active Alchemist workers:
    Worker-1 on C02V25U2HTD6 at 0.0.0.0:24961
    Worker-2 on C02V25U2HTD6 at 0.0.0.0:24962
    Worker-3 on C02V25U2HTD6 at 0.0.0.0:24963
No inactive Alchemist workers
Listing 3 assigned Alchemist workers:
    Worker-1 on C02V25U2HTD6 at 0.0.0.0:24961
    Worker-2 on C02V25U2HTD6 at 0.0.0.0:24962
    Worker-3 on C02V25U2HTD6 at 0.0.0.0:24963


In [10]:
lib_name = "TestLib"
lib_path = "/Users/payyalasom/Documents/HAL-priya/TestLib/target/testlib.dylib"
TestLib = als.load_library(lib_name,lib_path)


Library 'TestLib' at /Users/payyalasom/Documents/HAL-priya/TestLib/target/testlib.dylib successfully loaded.


In [11]:
input_matrix = [[1,2,3,4,5,6,7,8,9,10],
        [2,22,13,24,15,36,17,28,19,38],
        [3,22,13,24,15,36,17,28,19,38],
        [4,22,13,24,15,36,17,28,19,38],
        [5,22,13,24,15,36,17,28,19,38],
        [6,22,13,24,15,36,17,28,19,38],
        [7,22,13,24,15,36,17,28,19,38],
        [8,22,13,24,15,36,17,28,19,38],
        [9,22,13,24,15,36,17,28,19,38],
        [10,22,13,24,15,36,17,28,19,38]]

In [12]:
size_of_row_chunks = 5
size_of_col_chunks = 5


In [13]:
dask_matrix = da.from_array(input_matrix,chunks=(size_of_row_chunks,size_of_col_chunks,))


In [14]:
als.send_dask_matrix(matrix=dask_matrix, print_times=True, layout="VC_STAR")


Size of row chunks: 5
Size of col chunks: 5
Size of chunks: 25
Size of input matrix: 100
Number of total chunks: 4
Row size: 10
Column size: 10
Number of row chunks: 2
Number of column chunks: Ending Alchemist session
Closing socket
Closing driver client
Closing socket
2
slice_row_id 0
slice_col_id 0

printing the layer: (<built-in function getitem>, 'array-original-d45d093fdb1778c7ee20e6f0e319feb5', (slice(0, 5, None), slice(0, 5, None)))

printing the required array:
[[ 1  2  3  4  5]
 [ 2 22 13 24 15]
 [ 3 22 13 24 15]
 [ 4 22 13 24 15]
 [ 5 22 13 24 15]]

start row index 0
start column index 0
end row index 5
end col index 5
slice_row_id 0
slice_col_id 1

printing the layer: (<built-in function getitem>, 'array-original-d45d093fdb1778c7ee20e6f0e319feb5', (slice(0, 5, None), slice(5, 10, None)))

printing the required array:
[[ 6  7  8  9 10]
 [36 17 28 19 38]
 [36 17 28 19 38]
 [36 17 28 19 38]
 [36 17 28 19 38]]

start row index 0
start column index 5
end row index 5
end col index